#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: TPC-DS

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-spark-30:
    name: Test spark-3.0
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.0
      sparkurl: https://mirrors.huaweicloud.com/apache/spark/spark-3.0.3/spark-3.0.3-bin-hadoop2.7.tgz

  test-spark-31:
    name: Test spark-3.1
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.1
      sparkurl: https://mirrors.huaweicloud.com/apache/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz

  test-spark-32:
    name: Test spark-3.2
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.2
      sparkurl: https://mirrors.huaweicloud.com/apache/spark/spark-3.2.4/spark-3.2.4-bin-hadoop2.7.tgz

  test-spark-33:
    name: Test spark-3.3
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.3
      sparkurl: https://mirrors.huaweicloud.com/apache/spark/spark-3.3.4/spark-3.3.4-bin-hadoop3.tgz

  test-spark-34-jdk11:
    name: Test spark-3.4
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.4
      sparkurl: https://mirrors.huaweicloud.com/apache/spark/spark-3.4.3/spark-3.4.3-bin-hadoop3.tgz
      javaver: '11'

  test-spark-35-jdk17-scala-2-13:
    name: Test spark-3.5 JDK17 Scala-2.13
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.5
      sparkurl: https://archive.apache.org/dist/spark/spark-3.5.5/spark-3.5.5-bin-hadoop3-scala2.13.tgz
      javaver: '17'
      scalaver: '2.13'
